name: Deploy CRUD Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCR_SA_KEY }}

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/crud-service:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/crud-service:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy crud-service --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/crud-service:latest --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
